name: Test workflow
on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
jobs:
  test:
    strategy:
      matrix:
        node-version: [20.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Install packages
        run: npm install
      - name: Build code
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Update Coverage Badge
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main
